### ISSUE TITLE
Stepper motor jitters unless I reconnect power to IHM01A1

### ISSUE THREAD

**Issue by ShawnHymel** [stm32duino/X-NUCLEO-IHM01A1#4]
This is an odd problem that I am having trouble figuring out the cause. I have the [STEVAL-EDUKIT01](https://www.st.com/en/evaluation-tools/steval-edukit01.html) inverted pendulum kit that contains the IHM01A1 and NUCLEO-F401RE. I connected the stepper wiring as given in the instructions on that page. I used a multimeter to verify that the coils are correctly attached to the A+/- and B+/- screw terminals.

I tried running the example given in this repo as well as the pre-compiled binaries in [this project](https://www.st.com/en/embedded-software/x-cube-spn1.html#st-get-software). If there is any load on the stepper (e.g. the encoder and pendulum), the motor will jitter back and forth, barely moving at all. However, if I unplug the 12V supply from the IHM01A1 and plug it back in, the red flag LED (D2) will light up, but the stepper motor seems to work correctly.

If I press the reset button on my Nucleo board, the red flag LED goes out, but the motor returns to its jittery, non-functional state.

For now, my workaround is to start running stepper code (i.e. sending commands to the IHM01A1) before plugging in the 12V supply, but that's not ultimately useable. Any suggestions on how to troubleshoot this problem would be appreciated!

**Comment by ShawnHymel** [comment]
To help with debugging, I attached 4 oscilloscope probes to A/B +/-. All ground clips to Nucleo board GND.

Yellow: A+
Green: A-
Blue: B+
Red: B-

Photos:
1) Microcontroller reset. The stepper motor jitters in place. It will turn without the load attached, but the pulses still look like this.
![F0mvQDgacAI0ANS](https://github.com/stm32duino/X-NUCLEO-IHM01A1/assets/5232145/2f05af9c-4c08-4586-bc32-45da6455d9db)

2) Unplug and reconnect 12V while microcontroller was still running. The motor turns as expected with and without the load.
![F0mvQDhaMAYmqBR](https://github.com/stm32duino/X-NUCLEO-IHM01A1/assets/5232145/88fb6d80-3a57-4885-8082-190a27dfedc7)

**Comment by cparata** [comment]
Hello @ShawnHymel ,
so, if I well understood, you have the same issue also with the pre-compiled binaries of X-CUBE-SPN1. The Arduino library is derived from the X-CUBE-SPN1 package, so, if the issue is present on X-CUBE-SPN1 code, it's normal that the issue is also present in the Arduino library. Unfortunately, I'm not expert on this component. I will try to contact some experts on this motor driver and I will come back to you with a feedback.
Best Regards,
Carlo

**Comment by ShawnHymel** [comment]
Hi @cparata,

Thank you. I ordered a second IHM01A1 and tried it--the result is the same as above, so I think it is likely a software issue.

**Comment by cparata** [comment]
Hello @ShawnHymel ,
I talked with an ST expert on motor driver. What is the configuration for L6474 that you are using in your application? Could you share it? Did you try to increase the "Torque regulation current" parameter to 800 (mA)?
Best Regards,
Carlo

**Comment by ShawnHymel** [comment]
Hi @cparata,

I am running the [hello world example](https://github.com/stm32duino/X-NUCLEO-IHM01A1/blob/main/examples/X_NUCLEO_IHM01A1_HelloWorld/X_NUCLEO_IHM01A1_HelloWorld.ino) found in this repo. I increased the "torque regulation current" (5th parameter in the `L6474_init_t` struct) to 800. I get the same result: the stepper is weak and stutters unless I cycle power to the driver board while the code is running.

**Comment by cparata** [comment]
Hello @ShawnHymel ,
if the firmware apparently works when you unplug/plug the 12V supply, it means that it works better with the default settings in the registers of the motor driver (unplugging the supply, you are resetting the configuration in the motor driver registers). So, I suggest to increase the "torque regulation current" to 1300 (mA) that is the default value in the registers of the motor driver and see if in this way it is better. Unfortunately, I do not have access to the source code of the binary file of the firmware released with the [STEVAL-EDUKIT01](https://www.st.com/en/evaluation-tools/steval-edukit01.html), otherwise we could try to use the same configuration and see if it works also with the Arduino library. Anyway, it seems to me an issue of configuration, because the configuration used in this library probably is not valid for the motor used in the inverted pendulum kit.
Best Regards,
Carlo

**Comment by ShawnHymel** [comment]
Hi @cparata,

Thank you for the response! I tried setting the torque regulation current to 1300 in the config struct, but the stepper motor is still behaving in the same way. It seems to have little to no torque unless I toggle the power. If it helps, here is my config struct:

```
// Stepper config
L6474_init_t stepper_config = {
  10000,                             // Acceleration rate in pps^2. Range: (0..+inf)
  10000,                             // Deceleration rate in pps^2. Range: (0..+inf)
  5000,                             // Maximum speed in pps. Range: (30..10000]
  1000,                              // Minimum speed in pps. Range: [30..10000)
  1300,                              // Torque regulation current in mA. Range: 31.25mA to 4000mA
  L6474_OCD_TH_750mA,               // Overcurrent threshold (OCD_TH register)
  L6474_CONFIG_OC_SD_ENABLE,        // Overcurrent shutwdown (OC_SD field of CONFIG register)
  L6474_CONFIG_EN_TQREG_TVAL_USED,  // Torque regulation method (EN_TQREG field of CONFIG register)
  L6474_STEP_SEL_1_16,               // Step selection (STEP_SEL field of STEP_MODE register)
  L6474_SYNC_SEL_1_2,               // Sync selection (SYNC_SEL field of STEP_MODE register)
  L6474_FAST_STEP_12us,             // Fall time value (T_FAST field of T_FAST register). Range: 2us to 32us
  L6474_TOFF_FAST_8us,              // Maximum fast decay time (T_OFF field of T_FAST register). Range: 2us to 32us
  3,                                // Minimum ON time in us (TON_MIN register). Range: 0.5us to 64us
  21,                               // Minimum OFF time in us (TOFF_MIN register). Range: 0.5us to 64us
  L6474_CONFIG_TOFF_044us,          // Target Switching Period (field TOFF of CONFIG register)
  L6474_CONFIG_SR_320V_us,          // Slew rate (POW_SR field of CONFIG register)
  L6474_CONFIG_INT_16MHZ,           // Clock setting (OSC_CLK_SEL field of CONFIG register)
  L6474_ALARM_EN_OVERCURRENT |
  L6474_ALARM_EN_THERMAL_SHUTDOWN |
  L6474_ALARM_EN_THERMAL_WARNING |
  L6474_ALARM_EN_UNDERVOLTAGE |
  L6474_ALARM_EN_SW_TURN_ON |
  L6474_ALARM_EN_WRONG_NPERF_CMD    // Alarm (ALARM_EN register)
};
```

**Comment by cparata** [comment]
Hello @ShawnHymel ,
could you try this setting:

```
L6474_init_t init_s = {
  80,                              /* Acceleration rate in pps^2. Range: (0..+inf). */
  80,                              /* Deceleration rate in pps^2. Range: (0..+inf). */
  800,                             /* Maximum speed in pps. Range: (30..10000]. */
  100,                              /* Minimum speed in pps. Range: [30..10000). */
  1000,                              /* Torque regulation current in mA. Range: 31.25mA to 4000mA. */
  L6474_OCD_TH_3000mA,               /* Overcurrent threshold (OCD_TH register). */
  L6474_CONFIG_OC_SD_ENABLE,        /* Overcurrent shutwdown (OC_SD field of CONFIG register). */
  L6474_CONFIG_EN_TQREG_TVAL_USED,  /* Torque regulation method (EN_TQREG field of CONFIG register). */
  L6474_STEP_SEL_1_8,               /* Step selection (STEP_SEL field of STEP_MODE register). */
  L6474_SYNC_SEL_1_2,               /* Sync selection (SYNC_SEL field of STEP_MODE register). */
  L6474_FAST_STEP_12us,             /* Fall time value (T_FAST field of T_FAST register). Range: 2us to 32us. */
  L6474_TOFF_FAST_8us,              /* Maximum fast decay time (T_OFF field of T_FAST register). Range: 2us to 32us. */
  3,                                /* Minimum ON time in us (TON_MIN register). Range: 0.5us to 64us. */
  21,                               /* Minimum OFF time in us (TOFF_MIN register). Range: 0.5us to 64us. */
  L6474_CONFIG_TOFF_044us,          /* Target Switching Period (field TOFF of CONFIG register). */
  L6474_CONFIG_SR_320V_us,          /* Slew rate (POW_SR field of CONFIG register). */
  L6474_CONFIG_INT_16MHZ,           /* Clock setting (OSC_CLK_SEL field of CONFIG register). */
  L6474_ALARM_EN_OVERCURRENT |
  L6474_ALARM_EN_THERMAL_SHUTDOWN |
  L6474_ALARM_EN_THERMAL_WARNING |
  L6474_ALARM_EN_UNDERVOLTAGE |
  L6474_ALARM_EN_SW_TURN_ON |
  L6474_ALARM_EN_WRONG_NPERF_CMD    /* Alarm (ALARM_EN register). */
};
```

Besides I would like to know if you have the same issue also with the original binary firmware of the the inverted pendulum kit.
Best Regards,
Carlo

**Comment by ShawnHymel** [comment]
Hi @cparata,

It looks like changing the regulation current to 1000 mA and the overcurrent threshold to 3000mA did the trick. It still feels like the torque is slightly underpowered (unless I cycle power on the board/stepper motor), but I don't have a way to easily measure the torque at the moment. However, this is plenty good enough for my application. Thank you!
